apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gochuchamchi-image-updater-git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: gochuchamchi-image-updater-git-creds
    creationPolicy: Owner
    template:
      data:
        username: "{{ .Values.username }}"
        password: "{{ `{{ .pat }}` }}"
  data:
    - secretKey: pat
      remoteRef:
        key: "{{ .Values.writePatSecretName }}"
